version: '3'
services:
  database:
    build: ./database
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    volumes:
      - ./database/data:/var/lib/postgresql/data
  server:
    build: ./server
    ports:
      - '3000:3000'
    depends_on:
      - database
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      - server